functional:
  - пользователь должен иметь возможность зарегистрироваться на сайте
  - пользователь должен иметь  возможность авторизоваться на сайте
  - пользователь должен иметь возможность изменять имя в своем профиле
  - пользователь может сыграть в пробную игру без регистрации на сайте
  - пользователь дожен иметь возможность создать новую игру с другими пользователями, с другом, с ботом
  - пользователь может пригласить в игру друга
  - пользователь может отменить приглашение друга в игру
  - у пользователя есть возможность выбора языка после создания игры
  - пользователь может выбрать игру по уровню сложности 
  - пользователь может выбрать задачу по названию или тегам
  - пользователь должен иметь возможность отправлять сообщения в чате зарегистрированным пользователям 
  - пользователь должен иметь возможность отправлять личные сообщения другому игроку
  - польователь может видеть код своего соперника в режиме онлайн
  - пользователь должен иметь возможность менять уровень сложности игры
  - пользователь должен иметь возможность остановить   игру
  - пользователь должен иметь возможность возобновить игру
  - пользователь может просматривать историю своих игр
  - пользователь должен иметь возможность просматривать рейтинг других игроков
  - пользователь должен иметь возможность создать свой пакет задач
  - пользователь должен иметь возможность создать новый турнир
  - пользователь может просматривать свой рейтинг за определенный период времени
  - пользователь может просматривать рейтинг других пользователей
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть способен обслуживать необходимое количество пользователей без снижения производительности
  - Сайт должен быть простым и понятным в использовании
implicit:
  - для вступления в игру пользователь должен быть зарегистрирован и авторизован
  - пользователь не может редактировать чужой код
  - сайт должен быть безопасным 
  - личные данные пользователей должны быть защищены
  - сайт должен соответствовать всем применимым законам и правилам
  - сайт должен быть доступным, когда это необходимо