functional:
  - пользователь должен иметь возможность зарегистрироваться на сайте
  - пользователь должен иметь  возможность авторизоваться на сайте
  - Пользователь должен иметь возможность изменять имя в своем профиле
  - на экране должно отображаться главное меню игры
  - пользователь дожен иметь возможность создать новую игру
  - есть возможность выбора русского или английского языка после создания игры
  - пользователь может выбрать игру по уровню сложности 
  - пользователь может выбрать задачу по названию или тегам
  - пользователь должен иметь возможность общаться в чате с зарегистрированными пользователями 
  - пользователь должен иметь возможность отправлять личные сообщения другому игроку
  - пользователь может играть с другими пользователями, с другом и с ботом
  - пользователь может пригласить в игру друга
  - пользователь может отменить приглашение друга в игру
  - пользователь может получать очки
  - каждый игрок видит код своего соперника в режиме онлайн
  - пользователь должен иметь возможность менять уровень сложности игры
  - пользователь должен иметь возможность возобновить игру
  - завершенная игра должна быть доступна в записи
  - игра пользователя должна сохраняться
  - пользователь должен иметь возможность просматривать рейтинг других игроков
  - пользователь должен иметь возможность создать свою собственную задачу
  - пользователь может просматривать свой рейтинг за неделю, месяц и за все время
  - пользователь может просматривать рейтинг других пользователей
  - есть возможность посмотреть предстоящие и завершенные турниры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - для вступления в игру пользователь должен быть зарегистрирован и авторизован
  - пользователь должен быть зарегистрирован на Github
  - пользователь не может редактировать чужой код
  - сайт должен быть безопасным и данные пользователей должны быть защищены