functional:
  - пользователь должен иметь возможность зарегистрироваться на сайте
  - пользователь должен иметь возможность менять и сохранять настройки своего профиля
  - на экране должно отображаться главное меню игры
  - пользователь дожен иметь возможность создать новую игру
  - игра пользователя должна сохраняться
  - пользователь должен иметь возможность менять уровень сложности игры
  - пользователь должен иметь возможность возобновить игру
  - пользователь должен иметь возможность просматривать рейтинг пользователей игры
  - пользователь должен иметь возможность создать свою собственную задачу
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - для вступления в игру пользователь должен быть зарегистрирован и авторизован
  - пользователь должен быть зарегистрирован на Github